Repository kaiko-ai/eva, pull requests merged in 2024-03, with the labels that each got.

#315 Rename `CI.yaml` to `ci.yaml`
  .github/workflows/ci.yaml
Labels: ci

#322 Create a developer docs workflow
  .github/workflows/docs.yaml
  mkdocs.yml
  noxfile.py
  pdm.lock
  pyproject.toml
Labels: documentation, ci

#325 Update repo README
  README.md
  docs/images/eva-process.gif
  pyproject.toml
Labels: documentation

#333 Updated main `README` and documentation landing page
  README.md
  docs/images/eva-process.gif
  docs/index.md
  mkdocs.yml
  pyproject.toml
Labels: documentation

#329 Updated docs regarding config files download
  README.md
  docs/index.md
  docs/user-guide/getting-started/how_to_use.md
  docs/user-guide/getting-started/installation.md
  docs/user-guide/tutorials/offline_vs_online.md
Labels: documentation

#335 Update `README.md` hrefs from locals to urls
  README.md
Labels: documentation

#334 Rename docs deploy
  .github/workflows/docs.yaml
Labels: ci

#339 Bump dev version
  pyproject.toml
Labels: package-management

#340 Fix error message when vision distribution is missing
  src/eva/vision/__init__.py
Labels: documentation

#318 Add realease github workflow
  .github/workflows/ci.yaml
  .github/workflows/release.yaml
Labels: ci, package-management

#343 Bump version to `0.0.1`
  README.md
  pyproject.toml
Labels: documentation, package-management

#347 Update email in CoC
  .github/workflows/ci.yaml
  docs/CODE_OF_CONDUCT.md
Labels: documentation

#337 Print results table at the end of an evaluation session
  pdm.lock
  pyproject.toml
  src/eva/core/trainers/_recorder.py
  src/eva/core/trainers/functional.py
  src/eva/core/trainers/trainer.py
Labels: core
