Repository kaiko-ai/eva, pull requests merged in 2024-09, with the labels that each got.

#615 Bump major version `1.0.0`
  pyproject.toml
Labels: bump-version

#632 Corrected number of classes in `CoNSeP` configs
  configs/vision/pathology/offline/segmentation/consep.yaml
  configs/vision/pathology/online/segmentation/consep.yaml
  src/eva/vision/data/datasets/segmentation/consep.py
Labels: bug

#633 Refactoring of forward method in model wrapper classes
  src/eva/core/models/wrappers/base.py
  src/eva/core/models/wrappers/from_function.py
  src/eva/core/models/wrappers/huggingface.py
  src/eva/core/models/wrappers/onnx.py
  src/eva/vision/models/wrappers/from_registry.py
  src/eva/vision/models/wrappers/from_timm.py
Labels: refactoring

#640 Udpate `timm` & `torchmetrics` dependency
  configs/vision/pathology/offline/segmentation/bcss.yaml
  configs/vision/pathology/offline/segmentation/consep.yaml
  configs/vision/pathology/offline/segmentation/monusac.yaml
  configs/vision/pathology/offline/segmentation/total_segmentator_2d.yaml
  configs/vision/pathology/online/segmentation/bcss.yaml
  configs/vision/pathology/online/segmentation/consep.yaml
  configs/vision/pathology/online/segmentation/monusac.yaml
  configs/vision/pathology/online/segmentation/total_segmentator_2d.yaml
  configs/vision/radiology/offline/segmentation/lits.yaml
  configs/vision/radiology/online/segmentation/lits.yaml
  pdm.lock
  pyproject.toml
  src/eva/core/metrics/defaults/segmentation/multiclass.py
  src/eva/core/metrics/generalized_dice.py
  src/eva/core/metrics/mean_iou.py
  src/eva/vision/models/networks/backbones/pathology/kaiko.py
Labels: package-management
